site_name: AquaMind

theme:
  name: material

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Pipeline Overview: pipeline-overview.md
  - Methods & Implementation:
      - Tank Setup: tank-setup.md
      - Stage 1 - Frame Extraction: stage_1.md
      - Stage 2 - Annotation: stage_2.md
      - Stage 3 - Dataset Class: stage_3.md
  - Results: results.md
  - Discussion: discussion.md
  - Contributing: contributing.md
  - About: about.md
  - References: references.md

